### ISSUE TITLE
Webpack error

### ISSUE THREAD

**Issue by Druux** [jaredLunde/mini-virtual-list#2]
Getting a super weird error when building with webpack in production mode.

`passive_layout_effect_dist_module is not a function`.

Seems like the `@react-hook` dependency causing some issues. Have you guys already experienced something like that? Could someone point me in the right direction maybe?

**Comment by jaredLunde** [comment]
What version of Webpack? Can you put together a simple reproduction? This sounds like a Webpack issue or a problem in your config rather than something from either of these libraries.

**Comment by jaredLunde** [comment]
For context, the react hook library you're referencing is likely used in 100k+ Webpack projects without consequence.

**Comment by Druux** [comment]
Thanks for your response!
It seems like the webpack production setting
```
optimization: {
   concatenateModules: true
}
```
causes the issue.
Will investigate a little bit more and getting back to you.

**Comment by jaredLunde** [comment]
This has been fixed in the latest passive layout effect release. Something related to a change in webpack 5
